const $=(s)=>document.querySelector(s), $$=(s)=>document.querySelectorAll(s);
const menu=$('.menu'),nav=$('.topbar nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
const datasets={
slow:{word:'SLOW',reason:'Road construction on Telegraph Avenue is reducing nearby foot traffic.',action:'Try a lunch special from 12–2 PM and post a same-day offer.',impact:'A focused promotion may recover 12–18% of weekday sales.',visitors:43,sales:'$318',customers:4,traffic:'-28%',trend:[72,64,58,51,46,42,40,44,39,36,41,43]},
normal:{word:'NORMAL',reason:'Typical weekday activity with steady nearby traffic.',action:'Keep regular hours and promote today’s best seller.',impact:'Maintain stable sales and prepare for the evening rush.',visitors:84,sales:'$612',customers:9,traffic:'Normal',trend:[58,62,59,65,63,68,66,70,67,72,71,74]},
busy:{word:'BUSY',reason:'A community event near Lake Merritt is increasing foot traffic.',action:'Stay open one hour later and highlight fast-selling items.',impact:'The extra traffic could add 20–31% in daily revenue.',visitors:132,sales:'$1,084',customers:18,traffic:'+31%',trend:[42,49,55,60,68,73,78,84,88,82,94,100]}
};
let current='normal',business='Cafe';
function updateDashboard(){const d=datasets[current];$('#statusWord').textContent=d.word;$('#reasonText').textContent=d.reason;$('#actionText').textContent=d.action;$('#impactText').textContent=d.impact;$('#visitors').textContent=d.visitors;$('#sales').textContent=d.sales;$('#customers').textContent=d.customers;$('#traffic').textContent=d.traffic;$('#businessLabel').textContent=`${business} · Downtown Oakland`;drawChart(d.trend);renderMiniAlerts();}
function drawChart(values){const c=$('#trendChart'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.09)';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,(h/4)*i);ctx.lineTo(w,(h/4)*i);ctx.stroke()}const min=Math.min(...values)-5,max=Math.max(...values)+5;ctx.beginPath();values.forEach((v,i)=>{const x=i*(w/(values.length-1)),y=h-((v-min)/(max-min))*h*.78-15;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=current==='busy'?'#b7e51c':current==='slow'?'#ffb21c':'#16b7ff';ctx.lineWidth=5;ctx.stroke();values.forEach((v,i)=>{const x=i*(w/(values.length-1)),y=h-((v-min)/(max-min))*h*.78-15;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()})}
function renderMiniAlerts(){const stack=$('#alertStack');stack.innerHTML=current==='slow'?'<div class="mini-alert"><strong>Construction impact</strong><span>Telegraph Ave lane closure</span></div><div class="mini-alert"><strong>Suggestion</strong><span>Promote delivery and lunch offers</span></div>':current==='busy'?'<div class="mini-alert"><strong>Community event</strong><span>Night market starts at 5 PM</span></div><div class="mini-alert"><strong>Suggestion</strong><span>Prepare extra inventory</span></div>':'<div class="mini-alert"><strong>City-code reminder</strong><span>Outdoor sign renewal due soon</span></div>';}
$$('#statusSwitch button').forEach(b=>b.addEventListener('click',()=>{$$('#statusSwitch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.status;updateDashboard()}));
$$('#businessTypes button').forEach(b=>b.addEventListener('click',()=>{$$('#businessTypes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');business=b.dataset.business;updateDashboard()}));
const scenes={crime:{title:'Safety alert near Lake Merritt',body:'Sodaro suggests adjusting closing procedures, sharing the alert with staff, and offering pickup or delivery options.'},construction:{title:'Construction is reducing foot traffic',body:'The system connects the street closure to lower visits and recommends a timed promotion plus clearer wayfinding.'},event:{title:'Community event may increase visitors',body:'Sodaro recommends extending hours, preparing inventory, and posting an event-specific offer.'},code:{title:'Outdoor display rule changed',body:'A location-based alert explains the update in plain language and links it to the business owner’s next task.'}};
$$('[data-scene]').forEach(b=>b.addEventListener('click',()=>{const s=scenes[b.dataset.scene];$('#sceneDetail h3').textContent=s.title;$('#sceneDetail p').textContent=s.body;document.querySelector('#alerts').scrollIntoView({behavior:'smooth',block:'center'})}));
const input=$('#photoInput'),upload=$('#uploadButton'),preview=$('#previewWrap'),img=$('#previewImage'),empty=$('#resultEmpty'),scan=$('#scanState'),result=$('#inspectionResult'),bar=$('#progressBar');upload.addEventListener('click',()=>input.click());$('#scanAgain').addEventListener('click',()=>input.click());input.addEventListener('change',()=>{const file=input.files[0];if(!file)return;img.src=URL.createObjectURL(file);upload.hidden=true;preview.hidden=false;empty.hidden=true;result.hidden=true;scan.hidden=false;let p=0;bar.style.width='0%';const timer=setInterval(()=>{p+=Math.floor(Math.random()*16)+8;if(p>=100){p=100;clearInterval(timer);setTimeout(showResult,350)}bar.style.width=p+'%';},320)});
function showResult(){scan.hidden=true;result.hidden=false;const score=82+Math.floor(Math.random()*12);$('#scoreRing').textContent=score;$('#resultTitle').textContent=score>=88?'Likely ready':'Review recommended';$('#findingList').innerHTML='<li class="pass">Accessible entrance appears visible</li><li class="pass">Primary walkway appears open</li><li class="warn">Check outdoor sign permit and mounting height</li><li class="warn">Keep sidewalk display at least 36 inches clear</li>';}
updateDashboard();window.addEventListener('resize',()=>drawChart(datasets[current].trend));
